stages:
  prepare_data:
    cmd: python -m src.data.prepare_data
    deps:
      - src/data/prepare_data.py
      - data/raw/df_final.csv
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
      - models/encoder.pkl

  train_model:
    cmd: python -m src.models.train
    deps:
      - src/models/train.py
      - data/processed/X_train.csv
      - data/processed/y_train.csv
    outs:
      - models/best_model.pkl
    params:
      - model.xgboost.max_depth
      - model.xgboost.n_estimators
      - model.xgboost.learning_rate

  evaluate:
    cmd: python -m src.models.evaluate
    deps:
      - src/models/evaluate.py
      - data/processed/X_test.csv
      - data/processed/y_test.csv
    metrics:
      - evaluation/metrics.json
    plots:
      - evaluation/scatter_plot.png:
          template: scatter
          x: "true"
          y: "pred"
          x_label: "True value"
          y_label: "Predicted value"
          title: "True vs Predicted"
      - evaluation/predictions.csv:
          template: simple
      - evaluation/confusion_matrix.png:
          template: confusion_matrix